<?php
    if(isset($_GET['quanly'])){
        $link=$_GET['quanly'];
    }
    else{
        $link="";
    }
    if($link=='shop'){
        include('main/shop.php');
    }
    elseif($link=='tintuc'){
        include('main/tintuc.php');
    }
    elseif($link=='giohang'){
        include('main/giohang.php');
    }
    elseif($link=='lienhe'){
        include('main/lienhe.php');
    }
    elseif($link=='chitietsp'){
        include('main/chitietsp.php');
    }
    elseif($link=='dangnhap'){
        include('main/dangnhap.php');
    }
    elseif($link=='dangky'){
        include('main/dangky.php');
    }
    elseif($link=='timkiem'){
        include('main/timkiem.php');
    }
    elseif($link=='camon'){
        include('main/camon.php');
    }
    elseif($link=='doimatkhau'){
        include('main/doimatkhau.php');
    }
    elseif($link=='giaohang'){
        include('main/giaohang.php');
    }
    elseif($link=='thanhtoan'){
        include('main/thanhtoan.php');
    }
    elseif($link=='donhangchitiet'){
        include('main/donhangchitiet.php');
    }
    elseif($link=='lichsudonhang'){
        include('main/lichsudonhang.php');
    }
    elseif($link=='quenmatkhau'){
        include('main/quenmatkhau.php');
    }
    elseif($link=='reset_pass'){
        include('main/reset_pass.php');
    }
    elseif($link=='q_danhmuc'){
        include('main/sanpham_theodm.php');
    }
    else{
        include('main/home.php');
    }
?>